hmrc/personal-income-tax-submission-frontend

app/controllers/interest/TaxedInterestAmountController.scala
app/controllers/interest/UntaxedInterestAmountController.scala
app/forms/TaxedInterestAmountForm.scala
app/forms/UntaxedInterestAmountForm.scala
app/models/TaxedInterestModel.scala
app/models/UntaxedInterestModel.scala
app/views/interest/TaxedInterestAmountView.scala.html
app/views/interest/UntaxedInterestAmountView.scala.html
test/controllers/interest/TaxedInterestAmountControllerSpec.scala
test/controllers/interest/UntaxedInterestAmountControllerSpec.scala
test/forms/TaxedInterestAmountFormSpec.scala
test/forms/UntaxedInterestAmountFormSpec.scala
test/models/interest/UntaxedInterestModelSpec.scala
test/views/interest/TaxedInterestAmountViewSpec.scala

[SASS-201] updated taxed and untaxed account and amount names 

---

app/controllers/dividends/OtherUkDividendsAmountController.scala
app/controllers/dividends/UkDividendsAmountController.scala
app/controllers/interest/ChangeAccountAmountController.scala
app/forms/OtherDividendsAmountForm.scala
app/forms/PriorOrNewAmountForm.scala
app/forms/TaxedInterestAmountForm.scala
app/forms/UkDividendsAmountForm.scala
app/forms/UntaxedInterestAmountForm.scala
app/views/dividends/OtherUkDividendsAmountView.scala.html
app/views/dividends/UkDividendsAmountView.scala.html
app/views/interest/ChangeAccountAmountView.scala.html
app/views/interest/InterestAccountsView.scala.html
app/views/templates/helpers/InputHelper.scala.html
app/views/templates/helpers/PriorOrNewForm.scala.html
app/views/templates/inputs/YesNoChoice.scala.html
conf/app.routes
conf/messages
test/controllers/dividends/OtherUkDividendsAmountControllerSpec.scala
test/controllers/dividends/UkDividendsAmountControllerSpec.scala
test/controllers/interest/ChangeAccountAmountControllerSpec.scala
test/forms/OtherDividendsAmountFormSpec.scala
test/forms/PriorOrNewAmountFormSpec.scala
test/forms/TaxedInterestAmountFormSpec.scala
test/forms/UkDividendsAmountFormSpec.scala
test/forms/UntaxedInterestAmountFormSpec.scala
test/views/dividends/OtherDividendsAmountViewSpec.scala
test/views/dividends/UkDividendsAmountViewSpec.scala
test/views/interest/ChangeAccountAmountViewSpec.scala
test/views/interest/InterestAccountsViewSpec.scala

Addition of the change prior amount page and other tidy up tasks

SASS-198 : Added Change Prior amount page

---

app/controllers/predicates/AuthorisedAction.scala
app/views/authErrorPages/AgentAuthErrorPageView.scala.html
app/views/headerFooterTemplate/Layout.scala.html
app/views/templates/helpers/Heading.scala.html
conf/messages
it/utils/IntegrationTest.scala
test/utils/UnitTest.scala
test/utils/ViewTest.scala
test/views/helpers/AgentAuthErrorPageViewSpec.scala

Original SASS-337 branch had issues with rebasing and has been replaced with this

SASS-337-2 added agent auth error page

---

project/AppDependencies.scala
test/views/authErrorPages/AgentAuthErrorPageViewSpec.scala
test/views/authErrorPages/UnauthorisedUserErrorPageViewSpec.scala
test/views/authErrorPages/YouNeedAgentServicesViewSpec.scala
test/views/dividends/ReceiveOtherDividendsViewSpec.scala
test/views/dividends/ReceiveUkDividendsViewSpec.scala
test/views/dividends/UkDividendsAmountViewSpec.scala
test/views/errors/IndividualUnauthorisedViewSpec.scala
test/views/interest/ChangeAccountAmountViewSpec.scala
test/views/interest/InterestAccountsViewSpec.scala
test/views/interest/InterestCYAViewSpec.scala
test/views/interest/RemoveAccountViewSpec.scala
test/views/interest/TaxedInterestAmountViewSpec.scala
test/views/interest/TaxedInterestViewSpec.scala
test/views/interest/UntaxedInterestAmountViewSpec.scala
test/views/interest/UntaxedInterestViewSpec.scala
test/views/templates/InternalServerErrorTemplateSpec.scala
test/views/templates/NotFoundTemplateSpec.scala
test/views/templates/ServiceUnavailableTemplateSpec.scala
test/views/templates/TaxYearErrorTemplateSpec.scala
test/views/templates/TimeoutPageSpec.scala

Added jsoup tests for Welsh messages.
[SASS-515](https://jira.tools.tax.service.gov.uk/browse/SASS-515)

SASS-515 - Added Jsoup tests for Welsh messages

---

app/assets/stylesheets/application-ie-8.scss
app/assets/stylesheets/application.scss
app/views/headerFooterTemplate/BeforeBodyContent.scala.html

Hides the back link when javascript is not enabled in browser
[SASS-538](https://jira.tools.tax.service.gov.uk/browse/SASS-538)

SASS 538 - Hide back link when javascript is disabled

---

app/models/giftAid/GiftAidPaymentsModel.scala
app/models/giftAid/GiftAidSubmissionModel.scala
app/models/giftAid/GiftsModel.scala
it/connectors/GiftAidSubmissionConnectorSpec.scala
test/models/giftAid/GiftAidSubmissionModelSpec.scala

[[SASS-570]](https://jira.tools.tax.service.gov.uk/browse/SASS-570)

[SASS-570a] changing ints to BigDecimals, refactor submission model

---

app/controllers/dividends/OtherUkDividendsAmountController.scala
app/views/dividends/OtherUkDividendsAmountView.scala.html
conf/messages
conf/messages.cy
test/controllers/dividends/OtherUkDividendsAmountControllerSpec.scala
test/views/dividends/OtherDividendsAmountViewSpec.scala

Removed radio buttons and made content changes to OtherUkDividendsAmount page.
[SASS-574](https://jira.tools.tax.service.gov.uk/browse/SASS-574)

SASS-574 - Conditionally revealing content on OtherUkDividendsAmount

---

app/controllers/charity/GiftAidDonationsController.scala
app/views/charity/GiftAidDonationView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidDonationsControllerISpec.scala
test/controllers/charity/GiftAidDonationControllerSpec.scala
test/views/charity/GiftAidDonationViewSpec.scala

Added page for gift donation with tests.
[SASS-255](https://jira.tools.tax.service.gov.uk/browse/SASS-255)

Added Gift donation route

---

app/controllers/dividends/OtherUkDividendsAmountController.scala
app/views/dividends/OtherUkDividendsAmountView.scala.html

Removed the pre-populated amount box for prior data
[574](https://jira.tools.tax.service.gov.uk/browse/SASS-574)

[SASS-574] Conditionally revealing content on OtherUkDividends

---

app/audit/CreateOrAmendDividendsAuditDetail.scala
app/audit/CreateOrAmendInterestAuditDetail.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/interest/InterestCYAController.scala
app/controllers/predicates/AuthorisedAction.scala
app/models/User.scala
it/controllers/charity/GiftAidDonationsControllerISpec.scala
it/utils/IntegrationTest.scala
test/audit/CreateOrAmendDividendsAuditDetailSpec.scala
test/audit/CreateOrAmendInterestAuditDetailSpec.scala
test/controllers/dividends/DividendsCYAControllerSpec.scala
test/controllers/interest/InterestCYAControllerSpec.scala
test/controllers/predicates/AuthorisedActionSpec.scala
test/models/interest/InterestPriorSubmissionSpec.scala
test/utils/UnitTest.scala

As requested, we are now going to include the affinity group as part of the create/update audit events for logging purposes.
[SASS-604](https://jira.tools.tax.service.gov.uk/browse/SASS-604)

SASS-604 : Updated CYA Audit events to include Affinity Group

---

app/controllers/charity/GiftAidOneOffController.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/dividends/OtherUkDividendsAmountController.scala
app/controllers/dividends/ReceiveOtherUkDividendsController.scala
app/controllers/interest/AccountsController.scala
app/controllers/interest/InterestCYAController.scala
app/controllers/interest/RemoveAccountController.scala
app/controllers/interest/TaxedInterestAmountController.scala
app/controllers/interest/TaxedInterestController.scala
app/controllers/interest/UntaxedInterestAmountController.scala
app/controllers/interest/UntaxedInterestController.scala
app/views/charity/GiftAidDonationView.scala.html
app/views/charity/GiftAidOneOffView.scala.html
app/views/dividends/ReceiveOtherUkDividendsView.scala.html
app/views/dividends/ReceiveUkDividendsView.scala.html
app/views/interest/InterestAccountsView.scala.html
app/views/interest/RemoveAccountView.scala.html
app/views/interest/TaxedInterestView.scala.html
app/views/interest/UntaxedInterestView.scala.html
app/views/templates/helpers/InputRadio.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidDonatedAmountControllerISpec.scala
it/controllers/charity/GiftAidOneOffControllerISpec.scala
test/controllers/charity/GiftAidOneOffControllerSpec.scala
test/views/charity/GiftAidOneOffViewSpec.scala

[SASS-257](https://jira.tools.tax.service.gov.uk/browse/SASS-257)

[SASS-257] gift aid journey one off page

---

app/controllers/charity/OverseasGiftAidDonationsController.scala
app/views/charity/OverseasGiftAidDonationView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidDonationsControllerISpec.scala
it/controllers/charity/OverseasGiftAidDonationControllerISpec.scala
test/views/charity/OverseasGiftAidDonationViewSpec.scala

Fixed url link for charity page
Updated URL for charity donation
Added page for overseas donation
[SASS-516](https://jira.tools.tax.service.gov.uk/browse/SASS-516)

Created page for overseas gift donation

---

app/views/interest/InterestAccountsView.scala.html
app/views/templates/helpers/InputRadio.scala.html
app/views/templates/helpers/InputText.scala.html
test/views/interest/InterestAccountsViewSpec.scala

Updated the p tags in the helpers to be divs

Updated the <p> tags in the helpers to be <div>'s

---

conf/app.routes
conf/application.conf
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidDonatedAmountControllerISpec.scala
it/utils/IntegrationTest.scala
test/views/charity/GiftAidDonatedAmountViewSpec.scala
test/views/charity/GiftAidDonationViewSpec.scala
test/views/charity/GiftAidOneOffAmountViewSpec.scala
test/views/charity/GiftAidOneOffViewSpec.scala
test/views/charity/OverseasGiftAidDonationViewSpec.scala

[DM] [SASS-660] Fixed several incorrect page URLS and updated caption

---

app/controllers/charity/OverseasGiftAidDonationsController.scala

overseas radio error fix

---

app/views/charity/GiftAidOverseasAmountView.scala.html
test/views/charity/GiftAidOverseasAmountViewSpec.scala

Amended spacing around label on view 
[SASS-517](https://jira.tools.tax.service.gov.uk/browse/SASS-517)

SASS-517-2 minor formatting change on view

---

app/controllers/charity/OverseasGiftAidSummaryController.scala
app/views/charity/OverseasGiftAidSummaryView.scala.html
app/views/templates/helpers/InputRadio.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/OverseasGiftAidSummaryControllerISpec.scala
test/controllers/charity/OverseasGiftAidSummaryControllerSpec.scala
test/views/interest/InterestAccountsViewSpec.scala

[SASS-519](https://jira.tools.tax.service.gov.uk/browse/SASS-519)

[SASS-647] - added overseasGiftAidSummary page

---

app/controllers/charity/GiftAidAppendNextYearTaxAmountController.scala
app/forms/AmountForm.scala
app/views/charity/GiftAidAppendNextYearTaxAmountView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidAppendNextYearTaxAmountControllerSpec.scala
it/utils/ViewHelpers.scala
project/AppDependencies.scala
project/plugins.sbt

Adding the page to allow users to enter the amount of donations made after the end of the tax year they would like to attribute to the previous tax year.
[Relevant ticket](https://jira.tools.tax.service.gov.uk/browse/SASS-260)

[DM] [SASS-718] Added the append next year tax to this year page

---

app/controllers/charity/GiftAidLastTaxYearController.scala
app/views/charity/GiftAidLastTaxYearView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidLastTaxYearControllerISpec.scala

[SASS-715](https://jira.tools.tax.service.gov.uk/browse/SASS-261)

Sass 715 donation to previous tax Year

---

app/controllers/charity/GiftAidDonateLandOrPropertyController.scala
app/views/charity/GiftAidDonateLandOrPropertyView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidDonateLandOrPropertyControllerISpec.scala
it/utils/ViewHelpers.scala

Addition of Donation of Land or Property page with tests
[SASS-722](https://jira.tools.tax.service.gov.uk/browse/SASS-722)

SASS-722 : Added Donation of Land or Property page to gift aid section

---

app/controllers/charity/GiftAidTotalShareSecurityAmountController.scala
app/forms/AmountForm.scala
app/views/charity/GiftAidTotalShareSecurityAmountView.scala.html
conf/app.routes
conf/application.conf
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidAppendNextYearTaxAmountControllerSpec.scala
it/controllers/charity/GiftAidTotalShareSecurityAmountControllerSpec.scala
it/utils/IntegrationTest.scala

Adding the total share or securities amount donated page.
Updated the generic AmountForm to properly handle special characters.
[SASS-721](https://jira.tools.tax.service.gov.uk/browse/SASS-264)

[DM] [SASS-721] Added share or security page

---

app/controllers/charity/GiftAidSharesSecuritiesLandPropertyOverseasController.scala
app/views/charity/GiftAidSharesSecuritiesLandPropertyOverseasView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidSharesSecuritiesLandPropertyOverseasControllerISpec.scala

Creating page for donation of shares, securities, land or property to overseas charities
[[SASS-740]](https://jira.tools.tax.service.gov.uk/browse/SASS-524)

SASS-740 - Donation of shares, securities, land and property to overseas charities

---

app/controllers/charity/OverseasSharesLandSummaryController.scala
app/views/charity/OverseasSharesLandSummaryView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/OverseasSharesLandSummaryControllerISpec.scala
it/utils/ViewHelpers.scala

[SASS-743] - created overseas charity shares, land etc donations page

---

app/controllers/charity/OverseasGiftAidSummaryController.scala
app/views/charity/OverseasGiftAidSummaryView.scala.html
conf/messages
conf/messages.cy

[SASS-746](https://jira.tools.tax.service.gov.uk/browse/SASS-746)

SASS-746 plural or singular title for summary

---

app/views/interest/InterestAccountsView.scala.html
test/views/interest/InterestAccountsViewSpec.scala

Removal of a redundant span which is nested inside a div tag wrapper. 
[[SASS-748]](https://jira.tools.tax.service.gov.uk/browse/SASS-531)

[SASS-748] Removal of redundant span nested in div text hint wrapper

---

app/common/SessionValues.scala
app/connectors/GiftAidSubmissionConnector.scala
app/controllers/charity/GiftAidCYAController.scala
app/controllers/charity/GiftAidLastTaxYearController.scala
app/controllers/charity/GiftAidOverseasNameController.scala
app/controllers/charity/GiftAidOverseasSharesNameController.scala
app/controllers/dividends/DividendsCYAController.scala
app/models/charity/GiftAidCYAModel.scala
app/models/charity/prior/GiftAidPaymentsModel.scala
app/models/charity/prior/GiftAidSubmissionModel.scala
app/models/charity/prior/GiftsModel.scala
app/views/charity/GiftAidCYAView.scala.html
conf/app.routes
conf/application.conf
conf/messages
conf/messages.cy
it/connectors/GiftAidSubmissionConnectorSpec.scala
it/controllers/charity/GiftAidCYAControllerISpec.scala
it/controllers/charity/GiftAidLastTaxYearControllerISpec.scala
it/controllers/charity/GiftAidOverseasNameControllerISpec.scala
it/controllers/charity/GiftAidOverseasSharesNameControllerISpec.scala
it/utils/IntegrationTest.scala
test/models/charity/GiftAidCYAModelSpec.scala
test/models/charity/prior/GiftAidSubmissionModelSpec.scala

Added the CYA page, model and made a some minor changes to improve readability.
[SASS-744](https://jira.tools.tax.service.gov.uk/browse/SASS-267)

[DM] [SASS-744] Added CYA view + few minor qol improvements

---

app/views/charity/GiftAidSharesSecuritiesLandPropertyDonationView.scala.html
app/views/charity/GiftAidSharesSecuritiesLandPropertyOverseasView.scala.html
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidSharesSecuritiesLandPropertyDonationControllerISpec.scala
it/controllers/charity/GiftAidSharesSecuritiesLandPropertyOverseasControllerISpec.scala
it/controllers/charity/GiftAidTotalShareSecurityAmountControllerSpec.scala
it/controllers/charity/OverseasSharesSecuritiesLandPropertyAmountControllerSpec.scala

[SASS-767](https://jira.tools.tax.service.gov.uk/browse/SASS-767)

SASS-767 update h1 and add progressive disclosure

---

app/views/charity/GiftAidSharesSecuritiesLandPropertyDonationView.scala.html
app/views/charity/GiftAidSharesSecuritiesLandPropertyOverseasView.scala.html

removed spacing style from gift aid disclosure

---

app/forms/interest/TaxedInterestAmountForm.scala
app/forms/interest/UntaxedInterestAmountForm.scala
app/forms/validation/StringConstraints.scala
app/views/interest/TaxedInterestAmountView.scala.html
app/views/interest/UntaxedInterestAmountView.scala.html
app/views/templates/helpers/InputText.scala.html
conf/messages
conf/messages.cy
it/controllers/interest/TaxedInterestAmountControllerISpec.scala
it/controllers/interest/UntaxedInterestAmountControllerISpec.scala
it/utils/ViewHelpers.scala

Added validation to interest account name pages for maximum name length and character validation
[SASS-512](https://jira.tools.tax.service.gov.uk/browse/SASS-512)

[SASS-831] - interest account name character validation

---

app/controllers/charity/GiftAidLandOrPropertyAmountController.scala
app/controllers/interest/ChangeAccountAmountController.scala
app/forms/charity/GiftAidOverseasNameForm.scala
app/forms/charity/GiftAidOverseasSharesNameForm.scala
app/views/charity/GiftAidOverseasNameView.scala.html
app/views/charity/GiftAidOverseasSharesNameView.scala.html
app/views/dividends/OtherUkDividendsAmountView.scala.html
app/views/dividends/UkDividendsAmountView.scala.html
app/views/templates/helpers/ErrorSummary.scala.html
app/views/templates/helpers/InputText.scala.html
conf/messages
conf/messages.cy
test/forms/charity/GiftAidOverseasNameFormSpec.scala
test/forms/charity/GiftAidOverseasSharesNameFormSpec.scala

Changed character limits for name pages to reflect validation, refactored messages including ordering and generalisation.
[SASS-786b](https://jira.tools.tax.service.gov.uk/browse/SASS-690)

SASS-786b : Changed character limits for name pages, refactored messages

---

app/connectors/GiftAidSubmissionConnector.scala
app/controllers/charity/GiftAidCYAController.scala
app/services/GiftAidSubmissionService.scala
it/connectors/GiftAidSubmissionConnectorSpec.scala
it/controllers/charity/GiftAidCYAControllerISpec.scala
test/services/GiftAidSubmissionServiceSpec.scala

SASS-881 create giftAid Service

---

app/controllers/interest/AccountsController.scala
app/controllers/interest/TaxedInterestAmountController.scala
app/controllers/interest/UntaxedInterestAmountController.scala
app/forms/interest/TaxedInterestAmountForm.scala
app/forms/interest/UntaxedInterestAmountForm.scala
app/views/interest/InterestAccountsView.scala.html
app/views/interest/InterestCYAView.scala.html
app/views/interest/TaxedInterestAmountView.scala.html
app/views/interest/TaxedInterestView.scala.html
app/views/interest/UntaxedInterestAmountView.scala.html
app/views/interest/UntaxedInterestView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/interest/AccountsControllerISpec.scala
it/controllers/interest/ChangeAccountAmountControllerISpec.scala
it/controllers/interest/InterestCYAControllerISpec.scala
it/controllers/interest/TaxedInterestAmountControllerISpec.scala
it/controllers/interest/UntaxedInterestAmountControllerISpec.scala
test/forms/interest/TaxedInterestAmountFormSpec.scala
test/forms/interest/UntaxedInterestAmountFormSpec.scala
test/views/interest/InterestAccountsViewSpec.scala
test/views/interest/InterestCYAViewSpec.scala
test/views/interest/TaxedInterestViewSpec.scala
test/views/interest/UntaxedInterestViewSpec.scala

Interest Content Iterations
[SASS-493](https://jira.tools.tax.service.gov.uk/browse/SASS-493)

Sass 833 2

---

conf/messages
conf/messages.cy
test/views/interest/InterestCYAViewSpec.scala

Interest cya page heading update
[SASS-493](https://jira.tools.tax.service.gov.uk/browse/SASS-493)

SASS-493 interest cya page ehading update

---

app/audit/CreateOrAmendGiftAidAuditDetail.scala
app/controllers/charity/GiftAidCYAController.scala
test/audit/CreateOrAmendGiftAidAuditDetailSpec.scala

[SASS-496](https://jira.tools.tax.service.gov.uk/browse/SASS-496)

[SASS-496] gift aid audit

---

.github/PULL_REQUEST_TEMPLATE.md
app/controllers/interest/UntaxedInterestAmountController.scala
conf/application.conf
project/AppDependencies.scala

Config and dependency updates (We are not removing the default-src from the story as of 14/06/2020)
[SASS-728](https://jira.tools.tax.service.gov.uk/browse/SASS-728)

SASS-905 : csp Config and dependency updates

---

app/config/AppConfig.scala
app/config/ConfigKeys.scala
conf/application.conf
it/connectors/DividendsSubmissionConnectorSpec.scala
it/utils/IntegrationTest.scala
test/config/AppConfigSpec.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-951
the current pull request?
the current pull request?

SASS-951 - Refactored how microservice urls are setup in AppConfig

---

app/controllers/interest/TaxedInterestAmountController.scala
app/controllers/interest/UntaxedInterestAmountController.scala
app/forms/charity/GiftAidOverseasNameForm.scala
app/forms/charity/GiftAidOverseasSharesNameForm.scala
app/forms/interest/TaxedInterestAmountForm.scala
app/forms/interest/UntaxedInterestAmountForm.scala
app/forms/validation/StringConstraints.scala
it/controllers/interest/TaxedInterestAmountControllerISpec.scala
it/controllers/interest/UntaxedInterestAmountControllerISpec.scala
test/forms/interest/TaxedInterestAmountFormSpec.scala
test/forms/interest/UntaxedInterestAmountFormSpec.scala

Added Id Match check to allow the user to change existing account information without triggering duplicate name validation.
[SASS-973](https://jira.tools.tax.service.gov.uk/browse/SASS-973)

SASS-982 : Added ID check to duplicate name verification

---

conf/app.routes

Tidied and refactored routes file.

SASS-route-tidy : Rearranged and removed unused routes

---

conf/application.conf
project/AppDependencies.scala
project/plugins.sbt
test/config/MessagesSpec.scala

Added HTTPOnly cookie flag to app conf to fix existing ZAP Issue
[SASS-879](https://jira.tools.tax.service.gov.uk/browse/SASS-879)

SASS-879 : Added HTTPOnly cookie flag to App Conf

---

app/controllers/charity/DonationsToPreviousTaxYearController.scala
app/controllers/charity/GiftAidAppendNextYearTaxAmountController.scala
app/controllers/charity/GiftAidLastTaxYearController.scala
app/controllers/charity/GiftAidSharesSecuritiesLandPropertyDonationController.scala
app/controllers/charity/LastTaxYearAmountController.scala
app/controllers/predicates/AuthorisedAction.scala
it/controllers/charity/DonationsToPreviousTaxYearControllerISpec.scala
it/controllers/charity/GiftAidAppendNextYearTaxAmountControllerSpec.scala
it/controllers/charity/GiftAidLastTaxYearControllerISpec.scala
it/controllers/charity/GiftAidSharesSecuritiesLandPropertyDonationControllerISpec.scala
it/controllers/charity/LastTaxYearAmountControllerISpec.scala
it/utils/IntegrationTest.scala

Merge to help progress the ticket faster

[DM] [SASS-977-duane] Several pages updates

---

conf/messages.cy
it/controllers/dividends/DividendsCYAControllerISpec.scala
it/controllers/dividends/OtherUkDividendsAmountControllerISpec.scala
it/controllers/dividends/ReceiveOtherUkDividendsControllerISpec.scala
it/controllers/dividends/ReceiveUkDividendsControllerISpec.scala
it/controllers/dividends/UkDividendsAmountControllerISpec.scala
project/AppDependencies.scala
project/plugins.sbt
test/config/MessagesSpec.scala

Added the welsh messages for dividends and updated jsoup tests
[SASS-1128](https://jira.tools.tax.service.gov.uk/browse/SASS-993)

SASS-1128 - welsh content for dividends

---

conf/messages.cy
it/controllers/interest/AccountsControllerISpec.scala
it/controllers/interest/ChangeAccountAmountControllerISpec.scala
it/controllers/interest/ChooseAccountControllerISpec.scala
it/controllers/interest/InterestCYAControllerISpec.scala
it/controllers/interest/RemoveAccountControllerISpec.scala
it/controllers/interest/TaxedInterestAmountControllerISpec.scala
it/controllers/interest/TaxedInterestControllerISpec.scala
it/controllers/interest/UntaxedInterestAmountControllerISpec.scala
it/controllers/interest/UntaxedInterestControllerISpec.scala
project/AppDependencies.scala

Welsh content for interest journey added
[SASS-993](https://jira.tools.tax.service.gov.uk/browse/SASS-993)

Sass 993 - Welsh content for interest journey

---

app/controllers/charity/GiftAidOneOffAmountController.scala
app/controllers/charity/GiftAidOverseasAmountController.scala
app/controllers/charity/LastTaxYearAmountController.scala
app/controllers/charity/OverseasSharesSecuritiesLandPropertyAmountController.scala
app/forms/AmountForm.scala
app/forms/validation/mappings/Formatters.scala
app/forms/validation/mappings/MappingUtil.scala
conf/messages
conf/messages.cy
it/controllers/charity/DonationsToPreviousTaxYearControllerISpec.scala
it/controllers/charity/GiftAidOneOffAmountControllerISpec.scala
it/controllers/charity/GiftAidOverseasAmountControllerISpec.scala
it/controllers/charity/GiftAidOverseasNameControllerISpec.scala
it/controllers/charity/GiftAidOverseasSharesNameControllerISpec.scala
it/controllers/charity/LastTaxYearAmountControllerISpec.scala
it/controllers/charity/OverseasGiftAidDonationControllerISpec.scala
it/controllers/charity/OverseasSharesSecuritiesLandPropertyAmountControllerSpec.scala

[SASS-1071](https://jira.tools.tax.service.gov.uk/browse/SASS-1071)

[SASS-1173] - added errors for values exceeding amounts

---

app/forms/validation/StringConstraints.scala
test/forms/testUtils/StringConstraintsSpec.scala

Reverting the regex changes from SASS-1244 
https://github.com/hmrc/personal-income-tax-submission-frontend/pull/236

revert changes from SASS-1244

---

app/assets/stylesheets/application.scss
app/views/headerFooterTemplate/Head.scala.html
conf/application.conf
conf/prod.routes
it/controllers/charity/DonationsToPreviousTaxYearControllerISpec.scala
it/controllers/charity/GiftAidAppendNextYearTaxAmountControllerSpec.scala
it/controllers/charity/GiftAidCYAControllerISpec.scala
it/controllers/charity/GiftAidDonationsControllerISpec.scala
it/controllers/charity/GiftAidOneOffControllerISpec.scala
it/controllers/charity/OverseasGiftAidDonationControllerISpec.scala
it/controllers/dividends/DividendsCYAControllerISpec.scala
it/controllers/dividends/OtherUkDividendsAmountControllerISpec.scala
it/controllers/dividends/ReceiveOtherUkDividendsControllerISpec.scala
it/controllers/dividends/ReceiveUkDividendsControllerISpec.scala
it/controllers/dividends/UkDividendsAmountControllerISpec.scala
it/controllers/errors/SessionExpiredControllerISpec.scala
it/controllers/interest/AccountsControllerISpec.scala
it/controllers/interest/ChangeAccountAmountControllerISpec.scala
it/controllers/interest/ChooseAccountControllerISpec.scala
it/controllers/interest/InterestCYAControllerISpec.scala
it/controllers/interest/RemoveAccountControllerISpec.scala
it/controllers/interest/TaxedInterestAmountControllerISpec.scala
it/controllers/interest/TaxedInterestControllerISpec.scala
it/controllers/interest/UntaxedInterestAmountControllerISpec.scala
it/controllers/interest/UntaxedInterestControllerISpec.scala
it/utils/IntegrationTest.scala
it/utils/ViewHelpers.scala
test/config/MockAppConfig.scala
test/controllers/predicates/AuthorisedActionSpec.scala

Change all `/income-through-software/return/` strings to `/update-and-submit-income-tax-return/`
[SASS-1563](https://jira.tools.tax.service.gov.uk/browse/SASS-1563)

SASS-1563: Update personal FE page URLs

---

app/config/AppConfig.scala
conf/application.conf
test/config/MockAppConfig.scala

Adding feature switch for NRS Submission to personal-income-tax-submission-frontend
[SASS-1736](https://jira.tools.tax.service.gov.uk/browse/SASS-1641)

SASS-1736 Adding feature switch for NRS Submission

---

app/audit/CreateOrAmendInterestAuditDetail.scala
app/config/AppConfig.scala
app/config/ConfigKeys.scala
app/connectors/NrsConnector.scala
app/connectors/httpParsers/NrsSubmissionHttpParser.scala
app/controllers/charity/GiftAidCYAController.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/interest/InterestCYAController.scala
app/models/charity/DecodedGiftAidSubmissionPayload.scala
app/models/dividends/DecodedDividendsSubmissionPayload.scala
app/models/interest/DecodedInterestSubmissionPayload.scala
app/services/NrsService.scala
conf/application.conf
it/connectors/NrsConnectorSpec.scala
it/utils/IntegrationTest.scala
test/config/MockAppConfig.scala
test/services/NrsServiceSpec.scala

Connect the `personal-income-tax-submission-frontend` service to the `income-tax-nrs-proxy` service.
[SASS-179](https://jira.tools.tax.service.gov.uk/browse/SASS-179)

SASS-179: Connect Personal Income Tax Submission FE MS with Income-Tax-NRS-Proxy MS

---

app/connectors/httpParsers/NrsSubmissionHttpParser.scala
it/connectors/NrsConnectorSpec.scala
project/AppDependencies.scala

Changing NrsSubmission httpParser to handle and OK status rather than an accepted status
[SASS-1855](https://jira.tools.tax.service.gov.uk/browse/SASS-1855)

SASS-1855 Handle Ok status instead of Accepted in NrsSubmission HttpParser

---

app/services/NrsService.scala
app/utils/HMRCHeaderNames.scala
project/AppDependencies.scala
test/services/NrsServiceSpec.scala

Update personal FE to specify `User-Agent` and `True-User-Agent` headers for NRS submission.
[SASS-1934](https://jira.tools.tax.service.gov.uk/browse/SASS-1934)

SASS-1934: Update personal FE to specify user agent for NRS submission

---

README.md

[SASS-1817](https://jira.tools.tax.service.gov.uk/browse/SASS-1817)

[SASS-1817] update readMe

---

app/common/IncomeSources.scala
app/connectors/IncomeSourceConnector.scala
app/connectors/httpParsers/RefreshIncomeSourceHttpParser.scala
app/models/RefreshIncomeSourceRequest.scala
app/services/DividendsSessionService.scala
app/services/GiftAidSessionService.scala
app/services/InterestSessionService.scala
it/connectors/IncomeSourceConnectorSpec.scala
it/controllers/interest/InterestCYAControllerISpec.scala
it/helpers/WireMockHelper.scala
it/services/DividendsSessionServiceISpec.scala
it/services/GiftAidSessionServiceISpec.scala
it/services/InterestSessionServiceISpec.scala

[SASS-1321](https://jira.tools.tax.service.gov.uk/browse/SASS-1321)

[SASS-1321] cache fix

---

conf/prod.routes
project/AppDependencies.scala

Removing deprecated library
[SASS-2142](https://jira.tools.tax.service.gov.uk/browse/SASS-2083) (parent ticket)

[DM] [SASS-2142] removed deprecated dependency

---

app/views/charity/GiftAidQualifyingSharesSecuritiesView.scala.html
it/controllers/charity/GiftAidQualifyingSharesSecuritiesControllerISpec.scala
project/AppDependencies.scala

Added a details panel from one shares and securities page onto another, so the same information is available on each relevant page.
[SASS-2082](https://jira.tools.tax.service.gov.uk/browse/SASS-2082)

[DM] [SASS-2082] Added shares and securities text to page

---

app/controllers/interest/ChangeAccountAmountController.scala
app/controllers/interest/ChooseAccountController.scala
app/controllers/interest/InterestCYAController.scala
app/controllers/interest/RemoveAccountController.scala
app/controllers/interest/TaxedInterestAmountController.scala
app/controllers/interest/TaxedInterestController.scala
app/controllers/interest/UntaxedInterestAmountController.scala
app/models/interest/AccountAmountModel.scala
app/models/interest/InterestCYAModel.scala
app/models/interest/InterestPriorSubmission.scala
app/services/ChangeAccountAmountService.scala
app/services/ChooseAccountService.scala
app/services/RemoveAccountService.scala
app/services/TaxedInterestAmountService.scala
app/services/UntaxedInterestAmountService.scala
app/utils/SeqConversions.scala
test/models/interest/AccountAmountModelSpec.scala
test/models/interest/InterestCYAModelSpec.scala
test/services/ChangeAccountAmountServiceSpec.scala
test/services/ChooseAccountServiceSpec.scala
test/services/RemoveAccountServiceSpec.scala
test/services/TaxedInterestAmountServiceSpec.scala
test/services/UntaxedInterestAmountServiceSpec.scala
test/utils/SeqConversionsSpec.scala

Refactor logic from controllers into the service layer.
[SASS-1088](https://jira.tools.tax.service.gov.uk/browse/SASS-1088)

SASS-1088: Move some logic from controllers into service layer

---

app/views/charity/GiftAidAppendNextYearTaxAmountView.scala.html
app/views/charity/GiftAidDonatedAmountView.scala.html
app/views/charity/GiftAidLandOrPropertyAmountView.scala.html
app/views/charity/GiftAidOneOffAmountView.scala.html
app/views/charity/GiftAidOverseasAmountView.scala.html
app/views/charity/GiftAidTotalShareSecurityAmountView.scala.html
app/views/charity/LastTaxYearAmountView.scala.html
app/views/charity/OverseasSharesSecuritiesLandPropertyAmountView.scala.html
app/views/templates/helpers/InputTextAlt.scala.html
app/views/templates/helpers/P.scala.html
it/controllers/charity/GiftAidAppendNextYearTaxAmountControllerSpec.scala
it/controllers/charity/GiftAidDonatedAmountControllerISpec.scala
it/controllers/charity/GiftAidLandOrPropertyAmountControllerISpec.scala
it/controllers/charity/GiftAidOneOffAmountControllerISpec.scala
it/controllers/charity/GiftAidOverseasAmountControllerISpec.scala
it/controllers/charity/GiftAidTotalShareSecurityAmountControllerSpec.scala
it/controllers/charity/LastTaxYearAmountControllerISpec.scala
it/controllers/charity/OverseasSharesSecuritiesLandPropertyAmountControllerSpec.scala
project/AppDependencies.scala

Removed content from form labels and expedited to layout. Addition of alt text and layouts. Other clean up tasks.
[SASS-2034](https://jira.tools.tax.service.gov.uk/browse/SASS-2034)

SASS-2034 : Updated views to remove content from labels

---

project/AppDependencies.scala

[DM] [SASS-1958] Updated dependencies

---

app/assets/stylesheets/application.scss
project/AppDependencies.scala

[SASS-2332](https://jira.tools.tax.service.gov.uk/browse/SASS-2332)

[SASS-2332] Back link and language toggle layout

---

app/assets/stylesheets/itsa-print.css
app/views/headerFooterTemplate/Head.scala.html
app/views/headerFooterTemplate/Layout.scala.html
project/AppDependencies.scala

SASS-2523 fix to print preview styling.
[SASS-2523](https://jira.tools.tax.service.gov.uk/browse/SASS-2523)

SASS-2523 print preview styling

---

it/utils/TaxYearHelper.scala

 SASS-2720 - [FIX] Fixes issue with the TaxYearHelper.

---

app/controllers/interest/InterestCYAController.scala
app/controllers/interest/InterestGatewayController.scala
app/models/interest/InterestCYAModel.scala
app/services/EncryptionService.scala
app/views/interest/InterestGatewayView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/interest/AccountsControllerISpec.scala
it/controllers/interest/ChangeAccountAmountControllerISpec.scala
it/controllers/interest/InterestCYAControllerISpec.scala
it/controllers/interest/InterestGatewayControllerISpec.scala
it/controllers/interest/RemoveAccountControllerISpec.scala
it/controllers/interest/TaxedInterestAmountControllerISpec.scala
it/controllers/interest/TaxedInterestControllerISpec.scala
it/controllers/interest/UntaxedInterestAmountControllerISpec.scala
it/controllers/interest/UntaxedInterestControllerISpec.scala
it/services/InterestSessionServiceISpec.scala
it/utils/IntegrationTest.scala
test/audit/CreateOrAmendInterestAuditDetailSpec.scala
test/models/interest/EncryptedInterestCYAModelSpec.scala
test/models/interest/InterestCYAModelSpec.scala
test/services/InterestSubmissionServiceSpec.scala

Creation of interest gateway page
Parent ticket -> [SASS-11](https://jira.tools.tax.service.gov.uk/browse/SASS-11)

SASS-2863 Tailor interest gateway page

---

app/controllers/charity/GiftAidCYAController.scala
app/controllers/charity/GiftAidDonationsController.scala
app/controllers/charity/GiftAidGatewayController.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/dividends/ReceiveUkDividendsController.scala
app/models/charity/GiftAidCYAModel.scala
app/services/EncryptionService.scala
app/views/charity/GiftAidGatewayView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/charity/GiftAidCYAControllerISpec.scala
it/controllers/charity/GiftAidDonationsControllerISpec.scala
it/controllers/charity/GiftAidGatewayControllerISpec.scala
it/controllers/charity/GiftAidTotalShareSecurityAmountControllerSpec.scala
it/utils/IntegrationTest.scala
test/models/charity/GiftAidCYAModelSpec.scala

Adding the gateway page for charity
[SASS-18](https://jira.tools.tax.service.gov.uk/browse/SASS-18)

SASS-18 Add Charity Gateway Page

---

app/views/dividends/OtherUkDividendsAmountView.scala.html
app/views/dividends/UkDividendsAmountView.scala.html
conf/messages
conf/messages.cy
it/controllers/dividends/OtherUkDividendsAmountControllerISpec.scala
it/controllers/dividends/UkDividendsAmountControllerISpec.scala

Update amount and radio pages with explanatory text - Dividends Journey
[SASS-2214](https://jira.tools.tax.service.gov.uk/browse/SASS-2214)

SASS-2214 Update amount and radio pages with explanatory text - Dividends

---

app/controllers/ZeroingWarningController.scala
app/views/ZeroingWarningView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/ZeroingWarningControllerISpec.scala
it/controllers/charity/GiftAidCYAControllerISpec.scala
it/controllers/charity/GiftAidGatewayControllerISpec.scala
it/controllers/dividends/DividendsCYAControllerISpec.scala
it/controllers/dividends/DividendsGatewayControllerISpec.scala
it/controllers/dividends/OtherUkDividendsAmountControllerISpec.scala
it/controllers/dividends/ReceiveOtherUkDividendsControllerISpec.scala
it/controllers/dividends/ReceiveUkDividendsControllerISpec.scala
it/controllers/dividends/UkDividendsAmountControllerISpec.scala
it/controllers/interest/AccountsControllerISpec.scala
it/controllers/interest/ChangeAccountAmountControllerISpec.scala
it/controllers/interest/ChooseAccountControllerISpec.scala
it/controllers/interest/InterestCYAControllerISpec.scala
it/controllers/interest/InterestGatewayControllerISpec.scala
it/controllers/interest/RemoveAccountControllerISpec.scala
it/controllers/interest/TaxedInterestAmountControllerISpec.scala
it/controllers/interest/TaxedInterestControllerISpec.scala
it/controllers/interest/UntaxedInterestAmountControllerISpec.scala
it/controllers/interest/UntaxedInterestControllerISpec.scala
it/utils/CharityITHelper.scala
it/utils/DividendsDatabaseHelper.scala
it/utils/GiftAidDatabaseHelper.scala
it/utils/IntegrationTest.scala
it/utils/InterestDatabaseHelper.scala

Added a dynamic zeroing warning page for the interest, dividends and gift aid journeys.
[SASS-2928](https://jira.tools.tax.service.gov.uk/browse/SASS-2836)

[DM] [SASS-2928] Added Zeroing Warning page

---

app/views/dividends/ReceiveOtherUkDividendsView.scala.html
app/views/dividends/ReceiveUkDividendsView.scala.html
app/views/interest/ChangeAccountAmountView.scala.html
app/views/interest/TaxedInterestAmountView.scala.html
app/views/interest/TaxedInterestView.scala.html
app/views/interest/UntaxedInterestAmountView.scala.html
app/views/interest/UntaxedInterestView.scala.html
app/views/templates/helpers/InputTextAlt.scala.html
it/controllers/dividends/ReceiveOtherUkDividendsControllerISpec.scala
it/controllers/dividends/ReceiveUkDividendsControllerISpec.scala
it/controllers/interest/ChangeAccountAmountControllerISpec.scala
it/controllers/interest/TaxedInterestAmountControllerISpec.scala
it/controllers/interest/TaxedInterestControllerISpec.scala
it/controllers/interest/UntaxedInterestAmountControllerISpec.scala
it/controllers/interest/UntaxedInterestControllerISpec.scala

Removing page content inside form label - Interest Journey
[SASS-2213](https://jira.tools.tax.service.gov.uk/browse/SASS-2213)

SASS-2213 Page content inside form label

---

app/views/charity/GiftAidCYAView.scala.html
app/views/dividends/DividendsCYAView.scala.html
app/views/interest/InterestCYAView.scala.html
conf/messages
conf/messages.cy
it/config/MessagesISpec.scala
it/controllers/charity/GiftAidCYAControllerISpec.scala
it/controllers/dividends/DividendsCYAControllerISpec.scala
it/controllers/interest/InterestCYAControllerISpec.scala

Add gateway question line/field to Interest, Dividend and Donations CYA pages.
[SASS-2854](https://jira.tools.tax.service.gov.uk/browse/SASS-2854)

SASS-2854: Add Interest/Dividends/Donations to Charity Gateway question line to CYA pages

---

app/config/AppConfig.scala
app/config/ExcludeJourneyKeys.scala
app/connectors/ExcludeJourneyConnector.scala
app/connectors/httpParsers/ExcludeJourneyHttpParser.scala
app/controllers/ZeroingWarningController.scala
app/controllers/interest/InterestCYAController.scala
app/controllers/interest/InterestGatewayController.scala
app/models/interest/InterestCYAModel.scala
app/services/ExcludeJourneyService.scala
app/views/interest/InterestCYAView.scala.html
conf/application.conf
it/connectors/ExcludeJourneyConnectorISpec.scala
it/controllers/ZeroingWarningControllerISpec.scala
it/controllers/interest/InterestCYAControllerISpec.scala
it/utils/IntegrationTest.scala
test/config/MockAppConfig.scala
test/models/dividends/DividendsCheckYourAnswersModeSpec.scala

Updated to include the interest gateway journey when the tailoring feature switch is on.
[SASS-2975](https://jira.tools.tax.service.gov.uk/browse/SASS-2833)

[DM] [SASS-2975] Interest Gateway journey implemented

---

it/config/ErrorHandlerISpec.scala
it/controllers/ZeroingWarningControllerISpec.scala
it/controllers/charity/GiftAidCYAControllerISpec.scala
it/controllers/charity/GiftAidGatewayControllerISpec.scala
it/controllers/dividends/DividendsCYAControllerISpec.scala
it/controllers/dividends/DividendsGatewayControllerISpec.scala
it/controllers/errors/TaxYearErrorControllerISpec.scala
it/controllers/interest/InterestGatewayControllerISpec.scala
it/utils/IntegrationTest.scala
project/AppDependencies.scala
test/services/NrsServiceSpec.scala

[SASS-3123](https://jira.tools.tax.service.gov.uk/browse/SASS-3123)

SASS-3123 - Update bootstrap-BE/FE-play-28 dependencies

---

app/audit/TailorRemoveIncomeSourcesAuditDetail.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/interest/InterestCYAController.scala
test/audit/TailorRemoveIncomeSourcesAuditDetailSpec.scala

Create the audit event for removing income sources.
[SASS-2765](https://jira.tools.tax.service.gov.uk/browse/SASS-2765)

SASS-2765: Create TailorRemoveIncomeSources audit

---

app/controllers/charity/GiftAidCYAController.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/interest/InterestCYAController.scala

SASS-2757 TailorRemoveIncomeSources NRS request

SASS-2757 TailorRemoveIncomeSources NRS request

---

app/controllers/savings/TaxTakenFromInterestController.scala
app/views/savings/TaxTakenFromInterestView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/savings/TaxTakenFromInterestControllerISpec.scala

Created 'Was tax taken off your interest?' page
[SASS-3367](https://jira.tools.tax.service.gov.uk/browse/SASS-3367)

SASS-3367 added was tax taken off your interest page

---

app/controllers/interest/InterestSecuritiesCYAController.scala
app/models/interest/InterestSecuritiesCYAModel.scala
app/views/interest/InterestSecuritiesCYAView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/interest/InterestSecuritiesCYAControllerISpec.scala

Create interest from gilt-edged or accrued income securities check your answers page.
[SASS-3368](https://jira.tools.tax.service.gov.uk/browse/SASS-3368)

SASS-3368: Create 'Check Your Answers' page - Interest from gilt-edged or accrued income securities

---

app/views/templates/helpers/Heading.scala.html
build.sbt
it/controllers/errors/TaxYearErrorControllerISpec.scala
it/utils/IntegrationTest.scala
it/utils/ViewHelpers.scala
it/views/helpers/HeadingISpec.scala
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/controllers/predicates/TaxYearActionSpec.scala

Update the dependencies to the latest versions.
[SASS-3735](https://jira.tools.tax.service.gov.uk/browse/SASS-3735)

SASS-3735: Update dependencies for personal FE

---

project/AppDependencies.scala

Use the latest version of the mongo test library.
[SASS-3822](https://jira.tools.tax.service.gov.uk/browse/SASS-3822)

SASS-3822: Update mongo test version

---

app/controllers/predicates/AuthorisedAction.scala
it/helpers/WireMockHelper.scala
it/utils/IntegrationTest.scala
test/controllers/predicates/AuthorisedActionSpec.scala
test/utils/UnitTest.scala

Increasing the minimum Confidence Level value to 250 rather than 200
https://jira.tools.tax.service.gov.uk/browse/SASS-3946
SASS-3946 Increase the 'Confidence Level' to 250 from 200

SASS-3946 Increase the 'Confidence Level' to 250 from 200

---

app/views/charity/GiftAidGatewayView.scala.html
app/views/dividends/DividendsGatewayView.scala.html

[SASS-4656](https://jira.tools.tax.service.gov.uk/browse/SASS-4656)

SASS-4656 Accessibility - Fix Empty legends elements

---

app/views/interest/InterestAccountsView.scala.html
it/controllers/interest/AccountsControllerISpec.scala

Accessibility Interest - Summary_Lists_01
[SASS-4655](https://jira.tools.tax.service.gov.uk/browse/SASS-4655)

SASS-4655 Accessibility Interest - Summary_Lists_01

---

app/controllers/dividends/StockDividendAmountController.scala
app/views/dividends/StockDividendAmountView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/dividends/StockDividendAmountControllerISpec.scala

Create How much did you get in stock dividends page
[SASS-4001](https://jira.tools.tax.service.gov.uk/browse/SASS-4001)

SASS-4001 Create How much did you get in stock dividends page

---

app/controllers/dividends/CloseCompanyLoanAmountController.scala
app/views/dividends/CloseCompanyLoanAmountView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/dividends/CloseCompanyLoanAmountControllerISpec.scala

SASS-4465  https://jira.tools.tax.service.gov.uk/browse/SASS-4465

SASS-4465 Close company loan amount page

---

app/controllers/dividends/ReceiveUkStockDividendsController.scala
app/views/dividends/ReceiveUkStockDividendsView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/dividends/ReceiveUkStockDividendsControllerISpec.scala

[SASS-4000](https://jira.tools.tax.service.gov.uk/browse/SASS-4000)

SASS-4000: Create "Did you get stock dividends?" page - UK dividends

---

app/controllers/dividends/RedeemableSharesAmountController.scala
app/controllers/dividends/StockDividendAmountController.scala
app/controllers/dividends/StockDividendStatusController.scala
app/views/dividends/RedeemableSharesAmountView.scala.html
app/views/dividends/StockDividendStatusView.scala.html
conf/app.routes
conf/messages
conf/messages.cy
it/controllers/dividends/RedeemableSharesAmountControllerISpec.scala
it/controllers/dividends/StockDividendStatusControllerISpec.scala

[SASS-4463](https://jira.tools.tax.service.gov.uk/browse/SASS-4463)

SASS-4463 Create How much did you get in free or redeemable shares page

---

conf/application.conf

SASS-4536 Enable interst savings

---

app/common/IncomeSources.scala
app/connectors/StockDividendsUserDataConnector.scala
app/connectors/httpParsers/StockDividendsUserDataHttpParser.scala
app/controllers/dividends/StockDividendStatusController.scala
app/models/dividends/StockDividendsCheckYourAnswersModel.scala
app/models/dividends/StockDividendsPriorSubmission.scala
app/models/mongo/StockDividendsUserDataModel.scala
app/models/priorDataModels/StockDividendsPriorDataModel.scala
app/repositories/StockDividendsUserDataRepository.scala
app/services/EncryptionService.scala
app/services/StockDividendsSessionService.scala
it/connectors/StockDividendsUserDataConnectorISpec.scala
it/repositories/StockDividendsUserDataRepositoryISpec.scala
it/services/EncryptionServiceISpec.scala
it/services/StockDividendsSessionServiceISpec.scala
it/utils/IntegrationTest.scala
test/models/dividends/StockDividendsCheckYourAnswersModelSpec.scala
test/models/dividends/StockDividendsPriorSubmissionSpec.scala

[SASS-4822](https://jira.tools.tax.service.gov.uk/browse/SASS-4822)

SASS-4822 Create mongo store for stock dividends

---

app/audit/CreateOrAmendSavingsAuditDetail.scala
app/controllers/savings/InterestSecuritiesCYAController.scala
app/models/savings/DecodedSavingsSubmissionPayload.scala
test/audit/CreateOrAmendSavingsAuditDetailSpec.scala

SASS-4895 audit nrs savings

---

app/config/JourneyKeys.scala
app/connectors/httpParsers/StockDividendsSubmissionHttpParser.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/dividends/DividendsSummaryController.scala
app/controllers/dividends/OtherUkDividendsAmountController.scala
app/controllers/dividends/ReceiveOtherUkDividendsController.scala
app/controllers/dividends/ReceiveUkDividendsController.scala
app/controllers/dividends/StockDividendAmountController.scala
app/controllers/dividends/StockDividendStatusController.scala
app/controllers/dividends/UkDividendsAmountController.scala
app/models/dividends/StockDividendsCheckYourAnswersModel.scala
app/models/priorDataModels/StockDividendsPriorDataModel.scala
app/services/StockDividendsSubmissionService.scala
app/views/dividends/DividendsSummaryView.scala.html
conf/application.conf
it/controllers/dividends/CloseCompanyLoanAmountControllerISpec.scala
it/controllers/dividends/CloseCompanyLoanStatusControllerISpec.scala
it/controllers/dividends/DividendsSummaryControllerISpec.scala
it/controllers/dividends/OtherUkDividendsAmountControllerISpec.scala
it/controllers/dividends/ReceiveOtherUkDividendsControllerISpec.scala
it/controllers/dividends/ReceiveUkDividendsControllerISpec.scala
it/controllers/dividends/RedeemableSharesAmountControllerISpec.scala
it/controllers/dividends/RedeemableSharesStatusControllerISpec.scala
it/controllers/dividends/StockDividendAmountControllerISpec.scala
it/controllers/dividends/StockDividendStatusControllerISpec.scala
it/controllers/dividends/UkDividendsAmountControllerISpec.scala
it/utils/IntegrationTest.scala
project/AppDependencies.scala

Navigation of "UK companies" UK Dividends
[SASS-4004](https://jira.tools.tax.service.gov.uk/browse/SASS-4004)

Navigation of "UK companies" UK Dividends- Dividends

---

app/controllers/dividends/DividendsSummaryController.scala
app/models/dividends/StockDividendsCheckYourAnswersModel.scala
app/services/StockDividendsSubmissionService.scala
it/controllers/dividends/DividendsSummaryControllerISpec.scala
test/models/dividends/StockDividendsCheckYourAnswersModelSpec.scala
test/services/StockDividendsSubmissionServiceSpec.scala

Added logic in the service to only submit when values needed are present.
[SASS-5082](https://jira.tools.tax.service.gov.uk/browse/SASS-5082)

SASS-5082: Fix 500 error when in 'Stock Dividends' journey

---

app/controllers/dividends/DividendsCYAController.scala
app/controllers/dividends/DividendsGatewayController.scala
app/controllers/dividends/DividendsSummaryController.scala
app/controllers/dividends/OtherUkDividendsAmountController.scala
app/controllers/dividends/ReceiveOtherUkDividendsController.scala
app/controllers/dividends/ReceiveUkDividendsController.scala
app/controllers/dividends/UkDividendsAmountController.scala
app/views/dividends/DividendsSummaryView.scala.html
build.sbt
conf/application.conf
it/controllers/dividends/DividendsGatewayControllerISpec.scala
it/controllers/dividends/DividendsSummaryControllerISpec.scala
it/repositories/StockDividendsUserDataRepositoryISpec.scala
it/repositories/UserDataRepositoryISpec.scala
it/utils/IntegrationTest.scala
it/utils/InterestDatabaseHelper.scala
it/utils/SavingsDatabaseHelper.scala
project/AppDependencies.scala

Gateway page now uses stockDividends session when enabled, updated tests and some compiler warnings taken care of + dependency updates.
[SASS-5231](https://jira.tools.tax.service.gov.uk/browse/SASS-5231)

SASS-5231: gateway page fixes

---

app/views/dividends/RedeemableSharesStatusView.scala.html

[SASS-5433](https://jira.tools.tax.service.gov.uk/browse/SASS-5433)

SASS-5433 Accessibility fix missing legend text

---

app/views/templates/helpers/InputRadioAlt.scala.html
project/AppDependencies.scala

[SASS-5435](https://jira.tools.tax.service.gov.uk/browse/SASS-5435)

SASS-5435 Accessibility issue fix legend hidden text

---

app/audit/CreateOrAmendStockDividendsAuditDetail.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/dividends/DividendsSummaryController.scala
app/services/StockDividendsSubmissionService.scala
project/AppDependencies.scala
project/plugins.sbt
test/audit/CreateOrAmendStockDividendsAuditDetailSpec.scala
test/services/StockDividendsSubmissionServiceSpec.scala

Create Audit events for Stock Dividends
[SASS-5576](https://jira.tools.tax.service.gov.uk/browse/SASS-5576)

SASS-5576: Create Audit events for Stock Dividends

---

app/services/SavingsSubmissionService.scala
project/AppDependencies.scala
project/plugins.sbt
test/services/SavingsSubmissionServiceSpec.scala

Now submits optional value for foreign instead of an empty list if it did not exist.

SASS-7307: Update savings submission to match spec

---

app/controllers/dividends/DividendsCYAController.scala
app/controllers/savings/InterestSecuritiesCYAController.scala

update audit transaction name format

SASS-7472: update audit transaction name format

---

app/services/StockDividendsSubmissionService.scala
test/services/StockDividendsSubmissionServiceSpec.scala

Update stock dividends audit transaction name

SASS-7472: Update stock dividends audit transaction name

---

app/connectors/httpParsers/StockDividendsUserDataHttpParser.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/dividends/DividendsSummaryController.scala
app/models/priorDataModels/StockDividendsPriorDataModel.scala
app/services/StockDividendsSessionService.scala
app/services/StockDividendsSubmissionService.scala
it/test/connectors/StockDividendsUserDataConnectorISpec.scala
it/test/controllers/dividends/DividendsCYAControllerISpec.scala
it/test/controllers/dividends/DividendsSummaryControllerISpec.scala
it/test/utils/IntegrationTest.scala
project/plugins.sbt
test/services/StockDividendsSubmissionServiceSpec.scala

SASS-7856: Adjusting the Session Logic in CYA Controller

---

app/controllers/ZeroingWarningController.scala
app/controllers/dividends/DividendsGatewayController.scala
app/models/dividends/StockDividendsCheckYourAnswersModel.scala
conf/app.routes
conf/messages
conf/messages.cy
it/test/controllers/ZeroingWarningControllerISpec.scala
it/test/controllers/dividends/DividendsGatewayControllerISpec.scala
project/AppDependencies.scala
test/models/dividends/StockDividendsCheckYourAnswersModelSpec.scala

To enable Dividends to reflect on Excluded status when required
Linked to SASS-8028

SASS-8051: Added functionality to amend Stock Dividends values to zero

---

app/controllers/ZeroingWarningController.scala
app/models/dividends/StockDividendsPriorSubmission.scala

added comment to tack findings

Added comments to refer findings as part of qa issue fix for 8028

---

app/controllers/dividends/DividendsSummaryController.scala

SASS-8323 added clear session for dividends

---

app/common/IncomeSources.scala
app/services/SavingsSessionService.scala

Linked to the relevant story in Jira: SASS-8177

SASS-8409: Reverted IncomeSource value back to previous setting

---

app/controllers/ZeroingWarningController.scala
app/controllers/dividends/DividendsCYAController.scala
app/controllers/dividends/DividendsSummaryController.scala
app/models/dividends/DividendsCheckYourAnswersModel.scala
app/models/dividends/StockDividendsCheckYourAnswersModel.scala
app/services/DividendsSessionService.scala
app/services/DividendsSubmissionService.scala
app/services/StockDividendsSessionService.scala
app/services/StockDividendsSubmissionService.scala
conf/logback.xml
it/test/controllers/ZeroingWarningControllerISpec.scala
it/test/controllers/dividends/DividendsSummaryControllerISpec.scala
test/models/dividends/StockDividendsCheckYourAnswersModelSpec.scala
test/services/DividendsSubmissionServiceSpec.scala
test/services/StockDividendsSubmissionServiceSpec.scala

SASS-8322: Expanded scope of data for all related Dividends submissions to be sent to Downstream services

---

app/controllers/ZeroingWarningController.scala
app/controllers/dividends/DividendsSummaryController.scala
app/models/dividends/StockDividendsCheckYourAnswersModel.scala
app/services/StockDividendsSubmissionService.scala
it/test/controllers/ZeroingWarningControllerISpec.scala
it/test/controllers/dividends/DividendsSummaryControllerISpec.scala

SASS-8322_1: Changed criteria for zeroing Stock Dividends values

---

app/config/AppConfig.scala
app/controllers/dividends/DividendsSummaryController.scala
app/controllers/dividends/StockDividendStatusController.scala
app/controllers/dividendsBase/StockDividendAmountBaseController.scala
app/controllers/dividendsSplit/CheckStockDividendsAmountController.scala
app/controllers/dividendsSplit/StockDividendAmountSplitController.scala
app/models/dividends/StockDividendsCheckYourAnswersModel.scala
app/services/StockDividendsSessionServiceImpl.scala
app/views/dividends/CheckStockDividendsAmountView.scala.html
app/views/dividends/DividendsSummaryView.scala.html
app/views/dividends/StockDividendAmountView.scala.html
conf/app.routes
conf/application.conf
it/test/connectors/IncomeTaxUserDataConnectorSpec.scala
it/test/controllers/dividends/StockDividendAmountControllerISpec.scala
it/test/controllers/dividends/StockDividendAmountSplitControllerISpec.scala
it/test/controllers/dividends/StockDividendStatusControllerISpec.scala
it/test/controllers/dividendsBase/CheckStockDividendAmountControllerISpec.scala
it/test/controllers/dividendsBase/StockDividendAmountBaseControllerISpec.scala
it/test/controllers/dividendsSplit/StockDividendAmountSplitControllerISpec.scala
it/test/services/EncryptionServiceISpec.scala
it/test/services/StockDividendsBackendSessionServiceImplISpec.scala
it/test/utils/IntegrationTest.scala
test/config/MockAppConfig.scala

Allow stock dividend amount page to be it's own mini journey.

Sass 9627: Stock dividend amount mini journey

---

app/controllers/dividends/DividendsCYAController.scala
app/controllers/dividends/DividendsSummaryController.scala
app/controllers/dividends/OtherUkDividendsAmountController.scala
app/controllers/dividends/ReceiveOtherUkDividendsController.scala
app/controllers/dividends/StockDividendAmountController.scala
app/controllers/dividendsBase/OtherUkDividendsAmountBaseController.scala
app/controllers/dividendsSplit/CheckOtherUkDividendsAmountController.scala
app/controllers/dividendsSplit/OtherUkDividendsAmountSplitController.scala
app/models/dividends/DividendsCheckYourAnswersModel.scala
app/models/dividends/StockDividendsCheckYourAnswersModel.scala
app/services/StockDividendsSessionServiceImpl.scala
app/views/dividends/CheckOtherUkDividendsAmountView.scala.html
app/views/dividends/DividendsCYAView.scala.html
app/views/dividends/DividendsSummaryView.scala.html
conf/app.routes
it/test/controllers/dividends/OtherUkDividendsAmountControllerISpec.scala
it/test/controllers/dividends/ReceiveOtherUkDividendsControllerISpec.scala
it/test/controllers/dividendsBase/CheckOtherUkDividendsAmountControllerISpec.scala
it/test/controllers/dividendsBase/OtherUkDividendsAmountBaseControllerISpec.scala
it/test/controllers/dividendsSplit/OtherUkDividendsAmountSplitControllerISpec.scala
it/test/utils/IntegrationTest.scala
test/controllers/predicates/QuestionsJourneyValidatorTest.scala
test/models/dividends/DividendsCheckYourAnswersModeSpec.scala

SASS-9634: Implemented OtherUkDividendsAmount mini journey for Dividends section of new tasklist

---

app/views/templates/helpers/InputRadio.scala.html
app/views/templates/helpers/InputTextAlt.scala.html
it/test/utils/ViewHelpers.scala

SASS-9637 | Fixed Error not translated or appearing as visually hidden text

---

app/controllers/dividendsBase/CloseCompanyLoanAmountBaseController.scala
app/controllers/savings/SavingsInterestAmountController.scala
it/test/controllers/dividendsBase/CloseCompanyLoanAmountBaseControllerISpec.scala
it/test/controllers/dividendsSplit/CheckCloseCompanyLoanAmountControllerISpec.scala
it/test/controllers/dividendsSplit/CloseCompanyLoanAmountSplitControllerISpec.scala
it/test/controllers/dividendsSplit/RedeemableSharesAmountSplitControllerISpec.scala
it/test/controllers/dividendsSplit/UkDividendsAmountSplitControllerISpec.scala

Branch was created to include the latest work on this repo plus implementing Interest Savings Mini Journey with Integrations tests being refactored.
Linked to main ticket SASS-9960

SASS-9974_Updated: Additional refactoring of tests

---

app/utils/ViewUtils.scala

SASS-10112: Removing aria-hidden

---

app/views/interest/ChooseAccountView.scala.html
it/test/controllers/interest/ChooseAccountControllerISpec.scala

SASS-10111: Adding missed fieldset to which-account-did-you-get-taxed-interest-from page

---

app/views/headerFooterTemplate/Layout.scala.html
app/views/interest/InterestAccountsView.scala.html
build.sbt
conf/application.conf
project/AppDependencies.scala

Fix unquoted href attribute.
Update dependencies.

Sass 10113

---

app/forms/charity/GiftAidOverseasNameForm.scala
app/forms/charity/GiftAidOverseasSharesNameForm.scala
app/views/templates/helpers/InputText.scala.html
app/views/templates/helpers/InputTextAlt.scala.html
conf/messages
conf/messages.cy
it/test/controllers/charity/GiftAidOverseasNameControllerISpec.scala
it/test/controllers/charity/GiftAidOverseasSharesNameControllerISpec.scala
test/forms/charity/GiftAidOverseasNameFormSpec.scala
test/forms/charity/GiftAidOverseasSharesNameFormSpec.scala

SASS-10240: Unlimit textbox entry and error when chars greater than 500

---

app/config/AppConfig.scala
app/models/mongo/DividendsUserDataModel.scala
app/models/mongo/GiftAidUserDataModel.scala
app/models/mongo/InterestUserDataModel.scala
app/models/mongo/SavingsIncomeUserDataModel.scala
app/models/mongo/StockDividendsUserDataModel.scala
app/repositories/DividendsUserDataRepository.scala
app/repositories/StockDividendsUserDataRepository.scala
app/repositories/UserDataRepository.scala
conf/application.conf
it/test/repositories/UserDataRepositoryISpec.scala
it/test/utils/IntegrationTest.scala
test/config/MockAppConfig.scala

When Time To Live (TTL) has been set then data is stored in the database, the data should be remove once the TTL has expired.
Linked to main ticket SASS-9611

SASS-10237: Updated Models, UserRepository and configs with lastUpdated formatting

---

app/config/AppConfig.scala
app/controllers/SectionCompletedStateController.scala
app/controllers/charity/GiftAidCYAController.scala
app/models/Journey.scala
app/services/GiftAidSessionService.scala
app/services/SectionCompletedService.scala
conf/application.conf
it/test/controllers/charity/GiftAidCYAControllerISpec.scala
it/test/utils/IntegrationTest.scala
test/config/MockAppConfig.scala
test/models/JourneySpec.scala

SAss-10233

---

app/controllers/dividendsSplit/CheckCloseCompanyLoanAmountController.scala
app/controllers/dividendsSplit/CheckOtherUkDividendsAmountController.scala
app/controllers/dividendsSplit/CheckRedeemableSharesAmountController.scala
app/controllers/dividendsSplit/CheckStockDividendsAmountController.scala
app/controllers/dividendsSplit/CheckUkDividendsAmountController.scala
it/test/controllers/dividendsBase/CheckOtherUkDividendsAmountControllerISpec.scala
it/test/controllers/dividendsSplit/CheckCloseCompanyLoanAmountControllerISpec.scala
it/test/controllers/dividendsSplit/CheckRedeemableSharesAmountControllerISpec.scala
it/test/controllers/dividendsSplit/CheckStockDividendAmountControllerISpec.scala
it/test/controllers/dividendsSplit/CheckUkDividendsAmountControllerISpec.scala

SASS-10458 Tests fixed

---

app/views/dividends/DividendsGatewayView.scala.html
app/views/dividends/ReceiveUkDividendsView.scala.html
app/views/templates/helpers/InputRadioAlt.scala.html
conf/application.conf
it/test/controllers/dividends/DividendsGatewayControllerISpec.scala
it/test/controllers/dividends/ReceiveUkDividendsControllerISpec.scala
it/test/utils/ViewHelpers.scala
project/plugins.sbt

SASS-10684 Refactor hint on Dividends and update tests

---

app/config/ErrorHandler.scala
app/controllers/predicates/AuthorisedAction.scala
it/test/config/ErrorHandlerISpec.scala
it/test/utils/IntegrationTest.scala
test/config/MockErrorHandler.scala
test/controllers/predicates/AuthorisedActionSpec.scala
test/utils/UnitTest.scala

[SASS-10778] Update exception handling on AuthAction and update logging levels

---

app/views/charity/GiftAidLandOrPropertyAmountView.scala.html
app/views/charity/GiftAidTotalShareSecurityAmountView.scala.html
app/views/charity/OverseasSharesSecuritiesLandPropertyAmountView.scala.html
app/views/dividends/StockDividendAmountView.scala.html
app/views/dividends/UkDividendsAmountView.scala.html
app/views/interest/UntaxedInterestAmountView.scala.html
it/test/controllers/charity/GiftAidLandOrPropertyAmountControllerISpec.scala
it/test/controllers/charity/GiftAidTotalShareSecurityAmountControllerSpec.scala
it/test/controllers/charity/OverseasSharesSecuritiesLandPropertyAmountControllerSpec.scala
it/test/controllers/interest/UntaxedInterestAmountControllerISpec.scala

1. I have combined the following copy with the existing hint. "Give each account a different name.” and amended the tests
2. I have removed the additional copy "Total value, in pounds" from a number of views and amended the tests.
3. Fixed the heading and label not combined.
[SASS-10184](https://jira.tools.tax.service.gov.uk/browse/SASS-10184)

SASS-10185

---

README.md
app/config/AppConfig.scala
app/controllers/errors/SupportingAgentAuthErrorController.scala
app/controllers/predicates/AuthorisedAction.scala
app/utils/TaxYearHelper.scala
app/views/authErrorPages/SupportingAgentAuthErrorPageView.scala.html
build.sbt
check.sh
conf/app.routes
conf/application.conf
conf/messages
conf/messages.cy
project/AppDependencies.scala
project/plugins.sbt
test/config/MockAppConfig.scala
test/controllers/errors/SupportingAgentAuthErrorControllerSpec.scala
test/controllers/predicates/AuthorisedActionSpec.scala
test/utils/AesGcmAdCryptoSpec.scala
test/utils/ControllerUnitTest.scala

- Updated EMA blockers
- Updated dependencies
- Updated tests

SASS-11217: Enabling Multi-Agent for Personal-income-tax-submission-frontend

---

app/config/AppConfig.scala
app/connectors/SectionCompletedConnector.scala
app/controllers/charity/GiftAidCYAController.scala
app/controllers/predicates/AuthorisedAction.scala
app/controllers/predicates/TaxYearAction.scala
app/forms/AccountList.scala
app/repositories/DividendsUserDataRepository.scala
app/repositories/GiftAidUserDataRepository.scala
app/repositories/InterestUserDataRepository.scala
app/repositories/SavingsUserDataRepository.scala
app/repositories/StockDividendsUserDataRepository.scala
app/repositories/UserDataRepository.scala
app/services/ChangeAccountAmountService.scala
conf/application.conf
it/test/connectors/DividendsSubmissionConnectorSpec.scala
it/test/connectors/GiftAidSubmissionConnectorSpec.scala
it/test/connectors/InterestSubmissionConnectorISpec.scala
it/test/connectors/SavingsSubmissionConnectorISpec.scala
it/test/connectors/SectionCompletedConnectorISpec.scala
it/test/connectors/StockDividendsSubmissionConnectorSpec.scala
it/test/repositories/StockDividendsUserDataRepositoryISpec.scala
it/test/repositories/UserDataRepositoryISpec.scala
test/config/MockAppConfig.scala
test/controllers/predicates/AuthorisedActionSpec.scala
test/controllers/predicates/TaxYearActionSpec.scala

- SASS-11985 Fix warnings
- SASS-11985 Refactor repositories
- SASS-11985 Remove dead code in tests
- SASS-11985 Resolve some compiler warnings

SASS-11985 Resolve some compiler warnings 
